name: GitHub Actions Demo
on: [push]
jobs:
  vader-test-suite:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Git clone Vader
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: vader.vim
      - name: Git clone Fugitive
        uses: actions/checkout@v2
        with:
          repository: tpope/vim-fugitive
          path: vim-fugitive
      - name: List files in the repository
        run: |
          ls -R ${{ github.workspace }}/../
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: fugitive-gitlab.vim
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -R ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
